# Generated by Django 4.2 on 2024-05-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_read',
        ),
        migrations.AddField(
            model_name='email',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
